const svc:any = await import('@/lib/subchats/service');
console.log('RESULT exports:', Object.keys(svc).filter(k=>['createSubchat','markRead','unreadCount','revokeShare','renewShare','regenerateToken','renameSubchat','archiveSubchat','deleteSubchat','ensureGeneralSubchat','getSubchatActivity','postMessage'].includes(k)).sort().join(','));
const { createSubchat, postMessage, markRead, unreadCount, deleteSubchat, listMessages } = svc;
const { getDb } = await import('@/db/client');
const { subchat: sc } = createSubchat({ workspaceId: 'wp-smoke', title: 'Smoke', kind: 'external', external: false });
const me = 'user:smoke';
postMessage({ subchatId: sc.id, workspaceId: 'wp-smoke', authorKind: 'external', authorName: 'Kunde', content: 'hallo 1' });
postMessage({ subchatId: sc.id, workspaceId: 'wp-smoke', authorKind: 'system', authorName: null, content: 'system note' });
postMessage({ subchatId: sc.id, workspaceId: 'wp-smoke', authorKind: 'internal', authorId: me, authorName: 'Team', content: 'my own msg' });
postMessage({ subchatId: sc.id, workspaceId: 'wp-smoke', authorKind: 'external', authorName: 'Kunde', content: 'hallo 2' });
console.log('RESULT total:', listMessages(sc.id).length, '(expect 4)');
console.log('RESULT unread_no_marker:', unreadCount(sc.id, me), '(expect 2)');
markRead(sc.id, me);
console.log('RESULT unread_after_markread:', unreadCount(sc.id, me), '(expect 0)');
markRead(sc.id, me, 1);
const dbAny:any = getDb();
const marker:any = dbAny.$raw.prepare('SELECT last_read_ts FROM subchat_read_markers WHERE subchat_id=? AND user_id=?').get(sc.id, me);
console.log('RESULT monotonic_kept:', marker.last_read_ts > 1000000000000, '(expect true)');
deleteSubchat(sc.id);
const m:any = dbAny.$raw.prepare('SELECT COUNT(*) c FROM subchat_messages WHERE subchat_id=?').get(sc.id);
const k:any = dbAny.$raw.prepare('SELECT COUNT(*) c FROM subchat_read_markers WHERE subchat_id=?').get(sc.id);
console.log('RESULT after_delete msgs/markers:', m.c, k.c, '(expect 0 0)');
