/**
 * lib/deploy/scaffold.ts
 *
 * generateDeployScaffold — assembles the in-memory file list + pre-deploy notes
 * for a given DeployTarget.
 *
 * CONTRACT:
 *   - Returns {files, notes} — caller decides whether to write.
 *   - NEVER writes to disk (PHASE2_DEPLOY_WRITE marker below).
 *   - NEVER makes network calls.
 *   - Secrets/ENV values are NEVER embedded in any generated file.
 *   - notes[] always warn about dangerous dev-only ENV flags.
 *
 * PHASE2_DEPLOY_WRITE boundary:
 *   Actual file-writing is a gated (R3) action performed by the caller
 *   (e.g. scripts/gen-deploy.ts --write, or a future CI/CD step).
 *   This module is the read-only / planning layer.
 */

import type { DeployConfigInput, DeployScaffoldResult, DeployTarget, ScaffoldFile } from './targets';
import {
  generateCaddyfile,
  generateComposeFile,
  generateDockerfile,
  generateTailscaleServe,
  generateVercelConfig,
} from './generators';

// ---------------------------------------------------------------------------
// Pre-deploy notes (shared across targets)
// ---------------------------------------------------------------------------

/** Notes that are always included — target-independent safety warnings. */
function sharedNotes(input: DeployConfigInput): string[] {
  const { envKeys } = input;

  const requiredEnvWarnings = envKeys.map(
    (k) => `Required ENV key must be set before first boot: ${k}`,
  );

  return [
    // Security: dev-only flags must NEVER be present in production
    'SECURITY: LAZYOS_DEV_AUTO_LOGIN must NOT be set in production — it bypasses all authentication.',
    'SECURITY: LAZYOS_TEST_DISABLE_FK must NOT be set in production — it disables SQLite FK enforcement.',
    // FK enforcement reminder
    'Verify foreign-key enforcement is ON in production (FK enforcement is disabled only for test runs).',
    // Secrets
    'Secrets (AUTH_SECRET, ACCESS_CODE, CREDENTIAL_KEY) must be set via platform secret management — never committed to version control.',
    ...requiredEnvWarnings,
  ];
}

// ---------------------------------------------------------------------------
// Per-target assemblers
// ---------------------------------------------------------------------------

function buildVercel(input: DeployConfigInput): ScaffoldFile[] {
  return [
    {
      path: 'vercel.json',
      content: generateVercelConfig(input),
    },
    {
      path: '.env.example',
      content: buildEnvExample(input),
    },
  ];
}

function buildDocker(input: DeployConfigInput): ScaffoldFile[] {
  return [
    {
      path: 'Dockerfile',
      content: generateDockerfile(input),
    },
    {
      path: 'docker-compose.yml',
      content: generateComposeFile(input),
    },
    {
      path: '.env.example',
      content: buildEnvExample(input),
    },
  ];
}

function buildTailscale(input: DeployConfigInput): ScaffoldFile[] {
  return [
    {
      path: 'tailscale-serve.json',
      content: generateTailscaleServe(input),
    },
    {
      path: '.env.example',
      content: buildEnvExample(input),
    },
  ];
}

function buildCaddyVps(input: DeployConfigInput): ScaffoldFile[] {
  return [
    {
      path: 'Caddyfile',
      content: generateCaddyfile(input),
    },
    {
      path: '.env.example',
      content: buildEnvExample(input),
    },
  ];
}

// ---------------------------------------------------------------------------
// .env.example helper — key-names only, no values
// ---------------------------------------------------------------------------

function buildEnvExample(input: DeployConfigInput): string {
  const { appName, envKeys } = input;

  const lines = [
    `# ${appName} — environment variables`,
    `# Generated by lib/deploy/scaffold.ts (Batch 7e C5)`,
    `#`,
    `# Copy to .env.local and fill in the values.`,
    `# NEVER commit .env.local — it contains secrets.`,
    `# This file only contains key NAMES (no values).`,
    ``,
    `# --- Required (no defaults — app will not start without these) ---`,
  ];

  for (const key of envKeys) {
    lines.push(`${key}=`);
  }

  lines.push('');
  lines.push('# --- Optional runtime config ---');
  lines.push('# NODE_ENV=production');
  lines.push('# NEXT_TELEMETRY_DISABLED=1');
  lines.push(`# PORT=${input.webPort}`);
  lines.push(`# LAZYOS_DB_PATH=/data/lazyos.db`);
  lines.push('');
  lines.push('# --- Dev-only flags (NEVER set in production) ---');
  lines.push('# LAZYOS_DEV_AUTO_LOGIN=    <-- bypasses auth entirely — DANGER in prod');
  lines.push('# LAZYOS_TEST_DISABLE_FK=   <-- disables FK enforcement — DANGER in prod');

  return lines.join('\n') + '\n';
}

// ---------------------------------------------------------------------------
// Per-target notes
// ---------------------------------------------------------------------------

function targetNotes(target: DeployTarget, input: DeployConfigInput): string[] {
  const { appName, webPort, agentServerPort, domain } = input;
  const publicDomain = domain ?? `<your-domain>`;

  switch (target) {
    case 'vercel':
      return [
        `Vercel target: set all ENV keys in the Vercel dashboard or via "vercel env add <KEY> production".`,
        `Vercel target: the agent-server (port ${agentServerPort}) is NOT available on Vercel (serverless) — use docker/vps targets for full agent support.`,
        `Vercel target: verify output mode in next.config.ts — "standalone" output is commented out; re-enable if Vercel reports symlink errors.`,
        `Vercel target: project name in vercel.json is "${appName}" — must match Vercel project slug.`,
        `Vercel target: cron jobs (if any) require a Vercel Pro/Enterprise plan.`,
      ];

    case 'docker':
      return [
        `Docker target: build with "docker compose up --build" — first build takes ~3 min.`,
        `Docker target: the lazyos_data volume at /data holds lazyos.db — back it up before updates.`,
        `Docker target: agent-server on port ${agentServerPort} starts only if LAZYOS_CHAT_KEY is set AND the "claude" CLI is installed in the image (not bundled by default).`,
        `Docker target: to enable agent spawning, build a derived image that installs claude-code, or mount /root/.claude as a volume.`,
      ];

    case 'tailscale':
      return [
        `Tailscale target: run "tailscale up" on VPS before applying the serve config.`,
        `Tailscale target: apply with "tailscale serve --set-json <(cat tailscale-serve.json)".`,
        `Tailscale target: Tailscale MagicDNS hostname will be ${publicDomain}.`,
        `Tailscale target: Tailscale Funnel (internet exposure) is OFF by default — set AllowFunnel in config to enable.`,
        `Tailscale target: this config assumes ${appName} is already running on localhost:${webPort} (via systemd or docker).`,
      ];

    case 'caddy-vps':
      return [
        `Caddy-VPS target: Caddy must be installed (v2.7+) and DNS A/AAAA record for ${publicDomain} must point to this server's IP.`,
        `Caddy-VPS target: replace <ADMIN_EMAIL> in Caddyfile with a real email for ACME/Let's Encrypt TLS cert notifications.`,
        `Caddy-VPS target: apply with "caddy reload --config Caddyfile" (or "systemctl reload caddy").`,
        `Caddy-VPS target: ${appName} web process must be running on localhost:${webPort} (systemd lazyos-web.service or docker).`,
        `Caddy-VPS target: agent-server port (${agentServerPort}) is intentionally NOT proxied publicly — access via localhost or Tailscale only.`,
      ];
  }
}

// ---------------------------------------------------------------------------
// Main entry point
// ---------------------------------------------------------------------------

/**
 * generateDeployScaffold — the single public API of this module.
 *
 * Returns the full set of files + notes for the given target.
 * The caller is responsible for deciding whether to write the files to disk.
 *
 * PHASE2_DEPLOY_WRITE: actual disk writes happen in scripts/gen-deploy.ts
 * (--write flag, gated / R3 action) — NOT here.
 *
 * @param target - One of 'vercel' | 'docker' | 'tailscale' | 'caddy-vps'
 * @param input  - DeployConfigInput (no secret values — only key names)
 * @returns      { files: ScaffoldFile[], notes: string[] }
 */
export function generateDeployScaffold(
  target: DeployTarget,
  input: DeployConfigInput,
): DeployScaffoldResult {
  let files: ScaffoldFile[];

  switch (target) {
    case 'vercel':
      files = buildVercel(input);
      break;
    case 'docker':
      files = buildDocker(input);
      break;
    case 'tailscale':
      files = buildTailscale(input);
      break;
    case 'caddy-vps':
      files = buildCaddyVps(input);
      break;
    default: {
      // Exhaustiveness check — TypeScript narrows to `never` here.
      const _exhaustive: never = target;
      throw new Error(`Unknown deploy target: ${String(_exhaustive)}`);
    }
  }

  const notes = [
    ...sharedNotes(input),
    ...targetNotes(target, input),
  ];

  return { files, notes };
}
