import type { Metadata, Viewport } from "next";
import { cookies, headers } from "next/headers";
import "./globals.css";
import { TopNav } from "@/lib/nav/TopNav";
import { ScopeTabs } from "@/lib/nav/ScopeTabs";
import { CmdPalette } from "@/lib/cmd-palette/CmdPalette";
import { SwNavigationBridge } from "@/lib/pwa/SwNavigationBridge";
import { ToastProvider } from "@/lib/ui/tst/ToastProvider";
// PushAutoPrompt removed 2026-04-29 — overlay instead of surface library, user veto.
import { sniffLocale, SUPPORTED_LOCALES, type Locale } from "@/lib/i18n/dictionary";
import { BRAND_NAME } from "@/lib/brand";
import { DEFAULT_THEME_COLOR, resolveThemeColorFromOrg } from "./_viewport-theme";

export const metadata: Metadata = {
  title: BRAND_NAME,
  description:
    "Surface-First OS für 1-Mann-Agenturen. Pure Apple-Ästhetik, Event-Sourced, Multi-Plan-Orchestriert.",
  applicationName: BRAND_NAME,
  manifest: "/manifest.webmanifest",
  // Privacy sprint H3 (2026-05-01): noindex,nofollow as the default. Personal
  // data / internal audits / workspace structures must not end up in search engines.
  // Public marketing pages can set their own robots block.
  robots: {
    index: false,
    follow: false,
    nocache: true,
    googleBot: {
      index: false,
      follow: false,
    },
  },
  // Wave 5 (2026-05-01): iOS-PWA splash screens. Three resolutions
  // covering iPhone X/11/12/13/14 Pro, iPhone 14/15/16 Pro Max, and
  // iPhone 8 Plus. Generated by `scripts/generate-splash-screens.ts`
  // — User can replace with branded designs (same filenames).
  appleWebApp: {
    capable: true,
    statusBarStyle: "black-translucent",
    title: BRAND_NAME,
    startupImage: [
      "/apple-touch-startup-image-2436x1125.png",
      "/apple-touch-startup-image-2778x1284.png",
      "/apple-touch-startup-image-2208x1242.png",
    ],
  },
  icons: {
    icon: [
      { url: "/icon.svg", type: "image/svg+xml" },
      { url: "/icon-192.png", sizes: "192x192", type: "image/png" },
      { url: "/icon-512.png", sizes: "512x512", type: "image/png" },
    ],
    apple: [{ url: "/apple-touch-icon.png", sizes: "180x180", type: "image/png" }],
  },
};

// Wave 5b (2026-05-01): dynamic themeColor per segment cookie.
// generateViewport() reads the lazyos.org cookie and tints the iOS status bar
// to the workspace accent of the active org. Fallback to laz.ing black.
export async function generateViewport(): Promise<Viewport> {
  const c = await cookies();
  const orgId = c.get("lazyos.org")?.value;
  const themeColor = orgId ? resolveThemeColorFromOrg(orgId) : DEFAULT_THEME_COLOR;

  return {
    width: "device-width",
    initialScale: 1,
    // 2026-04-27: iOS zoom lock. minimum/maximum-scale locks the visual
    // viewport, so that neither input focus zooms in nor a previous
    // pinch-out state persistently shrinks the UI. Tradeoff: the user can
    // no longer pinch — acceptable for a chat app (standard like
    // Slack/iMessage).
    minimumScale: 1,
    maximumScale: 1,
    userScalable: false,
    viewportFit: "cover",
    themeColor,
    // iOS 17.4+ / Chrome 108+: the browser shrinks the layout viewport when
    // the keyboard opens instead of shifting the page. Standard for chat apps.
    interactiveWidget: "resizes-content",
  };
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Phase OSS.3 — server-side locale resolution.
  // Cookie `lazyos.locale` is the single source. Fallback: Accept-Language header
  // (sniffed for supported locales). Last resort: default 'de'.
  const c = await cookies();
  const h = await headers();
  const cookieLocale = c.get("lazyos.locale")?.value;
  let locale: Locale;
  if (cookieLocale && (SUPPORTED_LOCALES as readonly string[]).includes(cookieLocale)) {
    locale = cookieLocale as Locale;
  } else {
    const al = h.get("accept-language") ?? "";
    locale = sniffLocale(al);
  }

  return (
    <html lang={locale} data-locale={locale}>
      {/* Default segment matches the default workspace (lazyOS → accent='own').
          Hook will swap the class after hydration if a different workspace is
          persisted — keeping this in sync avoids a first-paint color flash. */}
      <body className="segment-own min-h-screen">
        <ToastProvider>
          <TopNav />
          {children}
          {/* Global iOS bottom tab bar (Phase 2 SP-4) — self-decides
              visibility (hidden ≥768px via CSS, not mounted on chat `/` or
              external sub-chats `/c/*`). Hosts the MobileDrawer mount for
              bar-visible routes (incl. /subchats/* where TopNav is null). */}
          <ScopeTabs />
          <CmdPalette />
          <SwNavigationBridge />
        </ToastProvider>
      </body>
    </html>
  );
}
