import type { Metadata, Viewport } from "next";
import { cookies, headers } from "next/headers";
import "./globals.css";
import { TopNav } from "@/lib/nav/TopNav";
import { CmdPalette } from "@/lib/cmd-palette/CmdPalette";
import { SwNavigationBridge } from "@/lib/pwa/SwNavigationBridge";
import { ToastProvider } from "@/lib/ui/tst/ToastProvider";
// PushAutoPrompt 2026-04-29 raus — Overlay statt Surface-Library, User-Veto.
import { sniffLocale, SUPPORTED_LOCALES, type Locale } from "@/lib/i18n/dictionary";
import { BRAND_NAME } from "@/lib/brand";
import { DEFAULT_THEME_COLOR, resolveThemeColorFromOrg } from "./_viewport-theme";

export const metadata: Metadata = {
  title: BRAND_NAME,
  description:
    "Surface-First OS für 1-Mann-Agenturen. Pure Apple-Ästhetik, Event-Sourced, Multi-Plan-Orchestriert.",
  applicationName: BRAND_NAME,
  manifest: "/manifest.webmanifest",
  // Privacy-Sprint H3 (2026-05-01): noindex,nofollow als Default. Persönliche
  // Daten / interne Audits / Workspace-Strukturen dürfen nicht in Suchmaschinen.
  // Public-Marketing-Pages können ihren eigenen robots-Block setzen.
  robots: {
    index: false,
    follow: false,
    nocache: true,
    googleBot: {
      index: false,
      follow: false,
    },
  },
  // Welle 5 (2026-05-01): iOS-PWA-Splash-Screens. Three Resolutions
  // covering iPhone X/11/12/13/14 Pro, iPhone 14/15/16 Pro Max, and
  // iPhone 8 Plus. Generated by `scripts/generate-splash-screens.ts`
  // — User can replace with branded designs (same filenames).
  appleWebApp: {
    capable: true,
    statusBarStyle: "black-translucent",
    title: BRAND_NAME,
    startupImage: [
      "/apple-touch-startup-image-2436x1125.png",
      "/apple-touch-startup-image-2778x1284.png",
      "/apple-touch-startup-image-2208x1242.png",
    ],
  },
  icons: {
    icon: [
      { url: "/icon.svg", type: "image/svg+xml" },
      { url: "/icon-192.png", sizes: "192x192", type: "image/png" },
      { url: "/icon-512.png", sizes: "512x512", type: "image/png" },
    ],
    apple: [{ url: "/apple-touch-icon.png", sizes: "180x180", type: "image/png" }],
  },
};

// Welle 5b (2026-05-01): dynamische themeColor per Segment-Cookie.
// generateViewport() liest lazyos.org-Cookie und färbt die iOS-Status-Bar
// auf den Workspace-Akzent der aktiven Org. Fallback auf laz.ing-Schwarz.
export async function generateViewport(): Promise<Viewport> {
  const c = await cookies();
  const orgId = c.get("lazyos.org")?.value;
  const themeColor = orgId ? resolveThemeColorFromOrg(orgId) : DEFAULT_THEME_COLOR;

  return {
    width: "device-width",
    initialScale: 1,
    // 2026-04-27: iOS-Zoom-Lock. minimum/maximum-Scale lockt das visuelle
    // Viewport, damit weder Input-Focus reinzoomt noch ein vorheriger
    // Pinch-Out-State persistent das UI verkleinert. Tradeoff: User kann
    // nicht mehr pinchen — bei einer Chat-App akzeptabel (Standard wie
    // Slack/iMessage).
    minimumScale: 1,
    maximumScale: 1,
    userScalable: false,
    viewportFit: "cover",
    themeColor,
    // iOS 17.4+ / Chrome 108+: Browser shrinkt das Layout-Viewport beim
    // Keyboard-Open statt die Page zu verschieben. Standard fuer Chat-Apps.
    interactiveWidget: "resizes-content",
  };
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Phase OSS.3 — Server-Side-Locale-Resolution.
  // Cookie `lazyos.locale` ist Single-Source. Fallback: Accept-Language Header
  // (gesnifft auf supported Locales). Last-Resort: Default 'de'.
  const c = await cookies();
  const h = await headers();
  const cookieLocale = c.get("lazyos.locale")?.value;
  let locale: Locale;
  if (cookieLocale && (SUPPORTED_LOCALES as readonly string[]).includes(cookieLocale)) {
    locale = cookieLocale as Locale;
  } else {
    const al = h.get("accept-language") ?? "";
    locale = sniffLocale(al);
  }

  return (
    <html lang={locale} data-locale={locale}>
      {/* Default segment matches the default workspace (lazyOS → accent='own').
          Hook will swap the class after hydration if a different workspace is
          persisted — keeping this in sync avoids a first-paint color flash. */}
      <body className="segment-own min-h-screen">
        <ToastProvider>
          <TopNav />
          {children}
          <CmdPalette />
          <SwNavigationBridge />
        </ToastProvider>
      </body>
    </html>
  );
}
