/**
 * Claude-Code Session-Registry
 * ----------------------------
 * Scanner über `~/.claude/projects/<project-slug>/*.jsonl` — liest alle
 * Claude-Code-Sessions (egal ob terminal-gestartet oder via lazyOS).
 *
 * Mapping: project slug `<projects-root-slug>-lazyos` → workspace `lazyos`.
 * The path is auto-generated by Claude-Code from the cwd; dots/slashes are
 * replaced with `-`.
 *
 * Pro Session lesen wir:
 *   - uuid (Dateiname ohne .jsonl)
 *   - path (absolute path zur .jsonl)
 *   - workspaceId (aus Slug rekonstruiert)
 *   - lastActivity (mtime)
 *   - bytes
 *   - turnCount (zählt 'user' type-events in JSONL)
 *   - lastPrompt (letzte 'last-prompt'-Zeile oder ersetzt durch letzten user-text)
 *   - active: ob aktuell in claude_sessions-Tabelle als aktive Workspace-Session markiert
 */

import fs from 'node:fs';
import path from 'node:path';

import { projectsRoot } from '@/lib/workspaces/projects-root';

export interface ClaudeSessionSummary {
  uuid: string;
  workspaceId: string | null;
  projectSlug: string;
  path: string;
  lastActivity: number; // unix ms
  bytes: number;
  turnCount: number;
  lastPrompt: string | null;
  /** Letzter Input-Token-Count aus dem letzten result-frame. */
  contextTotal: number;
  /** % vom 1M context-window (Opus-4.7-default), 0..100. */
  contextFillPct: number;
  /** True if this session-uuid is currently the "active" session of its workspace
   *  (as stored in claude_sessions table). */
  active?: boolean;
}

const HOME = process.env.HOME ?? '/root';
const CLAUDE_PROJECTS_DIR = path.join(HOME, '.claude', 'projects');

// Known mapping rules for project-slug → workspace-id.
// Claude-Code encodes the cwd as slashes-replaced-with-dashes, starting with -.
// Example (for projectsRoot() === "/srv/projects"):
//   /srv/projects/lazyos → -srv-projects-lazyos
//   /srv/projects/demo   → -srv-projects-demo
//   /root                → -root
//   /tmp                 → -tmp
// The prefix is derived from the configured projects root so it works on any
// host (LAZYOS_PROJECTS_ROOT) instead of a hardcoded path.
const PROJECTS_DIR_PREFIX = projectsRoot().replace(/\/+$/, '').replace(/\//g, '-') + '-';
const HOME_SLUG = HOME.replace(/\/+$/, '').replace(/\//g, '-');

function slugToWorkspaceId(slug: string): string | null {
  if (slug.startsWith(PROJECTS_DIR_PREFIX)) {
    return slug.slice(PROJECTS_DIR_PREFIX.length);
  }
  // Other conventions
  if (slug === '-root') return '(root)';
  if (slug === '-tmp') return '(tmp)';
  if (slug === HOME_SLUG) return '(home)';
  return null;
}

/**
 * Lightweight scan — liest tail (max 256 KB) der JSONL, zählt user-Turns
 * + extrahiert letzten Prompt. Format Claude-CLI ab 2.x:
 *   {"type":"user","message":{"role":"user","content":[{"type":"text",...}]}}
 *
 * Tail-Approach ist ein lower-bound bei sehr großen Files (> 256 KB), aber
 * für MVP ausreichend — die echten Sessions sind selten dauerhaft so groß.
 */
/**
 * Default-Context-Window für unbekannte Modelle. Opus 4.7 = 1M.
 * Wenn aus einem result-frame ein anderes Modell auftaucht, behandeln
 * wir das im usage-route via aktuellen Health-Check, nicht hier.
 */
const DEFAULT_CONTEXT_WINDOW = 1_000_000;

function summarizeFile(absPath: string): {
  turnCount: number;
  lastPrompt: string | null;
  bytes: number;
  lastActivity: number;
  contextTotal: number;
  contextFillPct: number;
} {
  const stat = fs.statSync(absPath);
  const bytes = stat.size;
  const lastActivity = stat.mtimeMs;

  const fd = fs.openSync(absPath, 'r');
  const readSize = Math.min(bytes, 256 * 1024);
  const buf = Buffer.alloc(readSize);
  try {
    fs.readSync(fd, buf, 0, readSize, Math.max(0, bytes - readSize));
  } finally {
    fs.closeSync(fd);
  }
  const tail = buf.toString('utf8');

  const tailLines = tail.split('\n').filter((l) => l.trim().length > 0);
  let turnCount = 0;
  let lastPrompt: string | null = null;
  let lastInput = 0;
  let lastCacheRead = 0;

  for (const line of tailLines) {
    try {
      const obj = JSON.parse(line) as {
        type?: string;
        message?: { role?: string; content?: unknown; usage?: unknown };
        usage?: unknown;
      };

      // Usage-Extraktion auf jedem Frame mit usage-Block (assistent + result).
      // Letzter gewinnt, deshalb keine break-Logic.
      const usage =
        (obj.message?.usage as Record<string, unknown> | undefined) ??
        (obj.usage as Record<string, unknown> | undefined);
      if (usage && typeof usage === 'object') {
        const inT =
          typeof usage.input_tokens === 'number' ? usage.input_tokens : 0;
        const cacheT =
          typeof usage.cache_read_input_tokens === 'number'
            ? usage.cache_read_input_tokens
            : 0;
        if (inT + cacheT > 0) {
          lastInput = inT;
          lastCacheRead = cacheT;
        }
      }

      if (obj.type !== 'user') continue;
      const blocks = obj.message?.content;
      if (!Array.isArray(blocks) || blocks.length === 0) continue;

      // Tool-Result-Frames (`{type: 'tool_result', ...}`) sind keine echten
      // Max-Prompts — die zählen wir nicht.
      const hasToolResult = blocks.some(
        (b) =>
          b &&
          typeof b === 'object' &&
          (b as { type?: unknown }).type === 'tool_result',
      );
      if (hasToolResult) continue;

      // Erster Text-Block ist der User-Prompt-Inhalt.
      const textBlock = blocks.find(
        (b) =>
          b &&
          typeof b === 'object' &&
          (b as { type?: unknown }).type === 'text',
      ) as { text?: unknown } | undefined;

      if (!textBlock) continue;
      turnCount++;
      const txt = typeof textBlock.text === 'string' ? textBlock.text : '';
      if (txt) lastPrompt = txt.replace(/\s+/g, ' ').slice(0, 140);
    } catch {
      // Skip malformed line
    }
  }

  const contextTotal = lastInput + lastCacheRead;
  const contextFillPct = Math.min(
    100,
    Math.round((contextTotal / DEFAULT_CONTEXT_WINDOW) * 100),
  );

  return {
    turnCount,
    lastPrompt,
    bytes,
    lastActivity,
    contextTotal,
    contextFillPct,
  };
}

/**
 * List all known Claude-Code sessions on disk.
 *
 * @param opts.workspaceId  Filter to one workspace.
 * @param opts.limit        Max sessions returned (default 100, across all workspaces).
 * @param opts.minActivityMs  Skip sessions older than this (filter out ancient noise).
 */
export function listClaudeSessions(opts?: {
  workspaceId?: string;
  limit?: number;
  minActivityMs?: number;
}): ClaudeSessionSummary[] {
  const limit = opts?.limit ?? 100;
  const minActivityMs = opts?.minActivityMs ?? 0;

  if (!fs.existsSync(CLAUDE_PROJECTS_DIR)) return [];

  const projectDirs = fs.readdirSync(CLAUDE_PROJECTS_DIR, { withFileTypes: true });

  const out: ClaudeSessionSummary[] = [];

  for (const entry of projectDirs) {
    if (!entry.isDirectory()) continue;
    const slug = entry.name;
    const workspaceId = slugToWorkspaceId(slug);
    if (opts?.workspaceId && workspaceId !== opts.workspaceId) continue;

    const projectPath = path.join(CLAUDE_PROJECTS_DIR, slug);
    let files: fs.Dirent[];
    try {
      files = fs.readdirSync(projectPath, { withFileTypes: true });
    } catch {
      continue;
    }

    for (const f of files) {
      if (!f.isFile() || !f.name.endsWith('.jsonl')) continue;
      const uuid = f.name.replace(/\.jsonl$/, '');
      const absPath = path.join(projectPath, f.name);
      let stat: ReturnType<typeof summarizeFile>;
      try {
        stat = summarizeFile(absPath);
      } catch {
        continue;
      }
      if (stat.lastActivity < minActivityMs) continue;

      out.push({
        uuid,
        workspaceId,
        projectSlug: slug,
        path: absPath,
        lastActivity: stat.lastActivity,
        bytes: stat.bytes,
        turnCount: stat.turnCount,
        lastPrompt: stat.lastPrompt,
        contextTotal: stat.contextTotal,
        contextFillPct: stat.contextFillPct,
      });
    }
  }

  out.sort((a, b) => b.lastActivity - a.lastActivity);
  return out.slice(0, limit);
}

/**
 * Look up which session-uuid is currently marked "active" for each workspace
 * in the claude_sessions table. Result merges with `listClaudeSessions`.
 *
 * Return: map workspaceId → uuid
 */
export function readActiveSessionMap(db: {
  prepare: (sql: string) => { all: () => Array<{ workspace_id: string; session_id: string }> };
}): Record<string, string> {
  try {
    const rows = db
      .prepare(
        `SELECT workspace_id, session_id FROM claude_sessions WHERE session_id IS NOT NULL`,
      )
      .all();
    const out: Record<string, string> = {};
    for (const r of rows) out[r.workspace_id] = r.session_id;
    return out;
  } catch {
    return {};
  }
}
