#!/usr/bin/env bash
# install-cli.sh — install `lazyos-cli` to /usr/local/bin.
#
# Creates a small wrapper script at /usr/local/bin/lazyos-cli that invokes
# tsx from the lazyos project's node_modules against
# scripts/lazyos-cli.ts. Using a wrapper (rather than a symlink) lets us:
#   - Pin the interpreter to the project's tsx (no PATH dependencies)
#   - Forward process.argv correctly
#   - Avoid shebang issues on minimal shells
#
# Idempotent: re-running is safe. Requires root (or sudo) to write into
# /usr/local/bin. Fails fast if tsx is missing.
set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TSX_BIN="$PROJECT_DIR/node_modules/.bin/tsx"
CLI_TS="$PROJECT_DIR/scripts/lazyos-cli.ts"
TARGET="/usr/local/bin/lazyos-cli"

if [[ ! -x "$TSX_BIN" ]]; then
  echo "error: tsx not found at $TSX_BIN" >&2
  echo "run 'pnpm install' in $PROJECT_DIR first" >&2
  exit 1
fi

if [[ ! -f "$CLI_TS" ]]; then
  echo "error: CLI source not found at $CLI_TS" >&2
  exit 1
fi

WRAPPER_CONTENT="#!/usr/bin/env bash
# lazyos-cli wrapper — auto-generated by scripts/install-cli.sh
# Regenerate via: bash $PROJECT_DIR/scripts/install-cli.sh
exec \"$TSX_BIN\" \"$CLI_TS\" \"\$@\"
"

if [[ "$EUID" -ne 0 ]]; then
  echo "info: writing $TARGET via sudo (needs root)"
  echo "$WRAPPER_CONTENT" | sudo tee "$TARGET" >/dev/null
  sudo chmod +x "$TARGET"
else
  printf '%s' "$WRAPPER_CONTENT" > "$TARGET"
  chmod +x "$TARGET"
fi

echo "installed: $TARGET"
echo "source:    $CLI_TS"
echo ""
echo "smoke-test:"
echo "  lazyos-cli workspace list"
