/**
 * lib/imagegen/codex-mcp.ts
 * -------------------------
 * Image generation via the Codex-MCP bridge (owner choice 2026-06-03).
 *
 * WHY MCP instead of `codex exec`?
 *   `codex exec` (non-interactive) has NO access to the built-in
 *   `image_gen` tool (OpenAI issue #19133) — only the interactive agent can
 *   generate images. `codex mcp-server` (stdio) starts EXACTLY this full
 *   agent as an MCP server and exposes a `codex` tool that runs a complete
 *   agent session — incl. `image_gen`. No OPENAI_API_KEY needed; it runs
 *   over the local MAX/ChatGPT subscription (~/.codex/auth.json).
 *
 * VERIFIED (2026-06-03, codex-cli 0.130.0): a `tools/call` on the
 * `codex` tool with an image prompt produces a real PNG (~1 MB) under
 * `~/.codex/generated_images/<threadId>/ig_*.png`. Latency ~85 s (TTFT ~35 s).
 *
 * SECURITY / DETERMINISM:
 *   - `sandbox: 'read-only'` (default): the agent may make NO shell/FS writes.
 *     The `image_gen` tool writes via its own privileged path
 *     to $CODEX_HOME — independent of the workspace sandbox. Read-only prevents
 *     the observed „ffmpeg-Umweg" (otherwise the model tries to fake the image
 *     via the shell).
 *   - `approval-policy: 'never'`: non-interactive, no approval prompts.
 *   - Strict prompt: ONLY `image_gen`, no shell/python/ffmpeg.
 *   - Single-flight (N11): max ONE generation at a time — image gen is
 *     expensive (~85 s, gpt-image server-side). Parallel calls → `image_gen_busy`.
 *
 * Pure Node (child_process + fs). No React, no Next-specific import —
 * importable from an API route OR a test harness.
 */

import { spawn, type ChildProcessWithoutNullStreams } from 'node:child_process';
import { existsSync, readdirSync, statSync } from 'node:fs';
import { homedir } from 'node:os';
import { join } from 'node:path';

const CODEX_BIN = process.env.LAZYOS_CODEX_BIN ?? 'codex';
const CODEX_HOME = process.env.CODEX_HOME ?? join(homedir(), '.codex');
const GEN_DIR = join(CODEX_HOME, 'generated_images');
const DEFAULT_TIMEOUT_MS = 180_000; // 3 min — image gen runs ~85 s, buffer for cold start.

/** Typed error for "a generation is already running" (N11 single-flight). */
export class ImageGenBusyError extends Error {
  constructor() {
    super('image_gen_busy');
    this.name = 'ImageGenBusyError';
  }
}

/** Typed error for "agent produced no image" (refusal / image_gen error). */
export class NoImageProducedError extends Error {
  constructor(detail: string) {
    super(`no_image_produced: ${detail}`);
    this.name = 'NoImageProducedError';
  }
}

export interface GenerateImageResult {
  /** Absolute path to the produced PNG (under ~/.codex/generated_images/...). */
  pngPath: string;
  /** Codex thread/conversation ID (= subfolder name), if captured. */
  threadId: string | null;
  /** Latency of the generation in ms. */
  latencyMs: number;
}

interface PngEntry {
  path: string;
  mtimeMs: number;
}

/** List all PNGs under GEN_DIR (recursively across the thread subfolders). */
function listPngs(restrictThreadId?: string | null): PngEntry[] {
  const out: PngEntry[] = [];
  if (!existsSync(GEN_DIR)) return out;
  const sessions = restrictThreadId ? [restrictThreadId] : readdirSync(GEN_DIR);
  for (const sess of sessions) {
    const sd = join(GEN_DIR, sess);
    let st;
    try {
      st = statSync(sd);
    } catch {
      continue;
    }
    if (!st.isDirectory()) continue;
    let files: string[];
    try {
      files = readdirSync(sd);
    } catch {
      continue;
    }
    for (const f of files) {
      if (!f.toLowerCase().endsWith('.png')) continue;
      const p = join(sd, f);
      try {
        out.push({ path: p, mtimeMs: statSync(p).mtimeMs });
      } catch {
        /* race: file disappeared */
      }
    }
  }
  return out;
}

/**
 * Strict system/user prompt that forces the agent to use ONLY `image_gen`
 * (no shell detour) and to produce exactly ONE image.
 */
function buildImagePrompt(userPrompt: string): string {
  return [
    'You are a single-purpose image generation service.',
    'Use ONLY your built-in `image_gen` tool to create EXACTLY ONE image.',
    'Do NOT use shell commands, ffmpeg, python, ImageMagick, or any other method —',
    'ONLY the built-in `image_gen` tool. Do not attempt to write any files yourself.',
    'Do not ask clarifying questions; make reasonable choices and generate directly.',
    '',
    'Image to generate (verbatim user request):',
    userPrompt,
    '',
    'After the image has been generated by `image_gen`, reply with ONLY the word DONE.',
  ].join('\n');
}

// N11 — single-flight: only ONE generation at a time.
let inFlight = false;

/**
 * Generates an image via the Codex-MCP bridge and returns the local PNG path.
 *
 * @throws {ImageGenBusyError}     when a generation is already running.
 * @throws {NoImageProducedError}  when no new PNG was produced.
 * @throws {Error}                 on spawn/timeout/abort errors.
 */
export async function generateImageViaCodex(opts: {
  prompt: string;
  signal?: AbortSignal;
  timeoutMs?: number;
  sandbox?: 'read-only' | 'workspace-write';
  model?: string;
}): Promise<GenerateImageResult> {
  if (inFlight) throw new ImageGenBusyError();
  inFlight = true;
  try {
    return await runGeneration(opts);
  } finally {
    inFlight = false;
  }
}

function runGeneration(opts: {
  prompt: string;
  signal?: AbortSignal;
  timeoutMs?: number;
  sandbox?: 'read-only' | 'workspace-write';
  model?: string;
}): Promise<GenerateImageResult> {
  const t0 = Date.now();
  const timeoutMs = opts.timeoutMs ?? DEFAULT_TIMEOUT_MS;
  const sandbox = opts.sandbox ?? 'read-only';
  const model = opts.model || process.env.LAZYOS_IMAGEGEN_MODEL || 'gpt-5.5';

  // Baseline PNGs BEFORE the run — fallback detection in case the threadId
  // cannot be read from the notifications.
  const before = new Set(listPngs().map((x) => x.path));

  return new Promise<GenerateImageResult>((resolve, reject) => {
    let child: ChildProcessWithoutNullStreams;
    try {
      child = spawn(CODEX_BIN, ['mcp-server'], { stdio: ['pipe', 'pipe', 'pipe'] });
    } catch (err) {
      reject(err instanceof Error ? err : new Error(String(err)));
      return;
    }

    let buf = '';
    let nextId = 1;
    let threadId: string | null = null;
    let settled = false;
    const pending = new Map<number, (msg: Record<string, unknown>) => void>();
    let stderrTail = '';

    const cleanup = (): void => {
      try {
        child.kill('SIGTERM');
      } catch {
        /* ignore */
      }
      clearTimeout(timer);
      if (opts.signal) opts.signal.removeEventListener('abort', onAbort);
    };
    const done = (
      fn: () => void,
    ): void => {
      if (settled) return;
      settled = true;
      cleanup();
      fn();
    };
    const fail = (err: Error): void => done(() => reject(err));

    const timer = setTimeout(() => {
      fail(new Error(`codex-imagegen timeout after ${timeoutMs}ms`));
    }, timeoutMs);

    const onAbort = (): void => fail(new Error('aborted'));
    if (opts.signal) {
      if (opts.signal.aborted) {
        fail(new Error('aborted'));
        return;
      }
      opts.signal.addEventListener('abort', onAbort, { once: true });
    }

    const writeMsg = (obj: Record<string, unknown>): void => {
      try {
        child.stdin.write(JSON.stringify(obj) + '\n');
      } catch (err) {
        fail(err instanceof Error ? err : new Error(String(err)));
      }
    };
    const request = (
      method: string,
      params: Record<string, unknown>,
    ): Promise<Record<string, unknown>> => {
      const id = nextId++;
      writeMsg({ jsonrpc: '2.0', id, method, params });
      return new Promise((res) => pending.set(id, res));
    };
    const notify = (method: string, params: Record<string, unknown>): void => {
      writeMsg({ jsonrpc: '2.0', method, params });
    };

    /** Locate the freshest PNG produced by this run. */
    const resolveProducedPng = (): void => {
      // Preferred: only the thread folder of this run.
      let candidates = listPngs(threadId).filter((p) => !before.has(p.path));
      // Fallback: any new PNG globally (threadId not captured).
      if (candidates.length === 0) {
        candidates = listPngs().filter((p) => !before.has(p.path));
      }
      if (candidates.length === 0) {
        fail(new NoImageProducedError('kein neues PNG unter ~/.codex/generated_images'));
        return;
      }
      candidates.sort((a, b) => b.mtimeMs - a.mtimeMs);
      done(() =>
        resolve({
          pngPath: candidates[0]!.path,
          threadId,
          latencyMs: Date.now() - t0,
        }),
      );
    };

    child.on('error', (err) => fail(err));
    child.stderr.on('data', (d: Buffer) => {
      stderrTail = (stderrTail + d.toString('utf8')).slice(-2000);
    });
    child.on('exit', (code) => {
      // Clean exit without resolve = error.
      if (!settled) {
        fail(
          new Error(
            `codex mcp-server exited (code ${code}) before producing an image. stderr: ${stderrTail.slice(-400)}`,
          ),
        );
      }
    });

    child.stdout.on('data', (d: Buffer) => {
      buf += d.toString('utf8');
      let nl: number;
      while ((nl = buf.indexOf('\n')) >= 0) {
        const line = buf.slice(0, nl).trim();
        buf = buf.slice(nl + 1);
        if (!line) continue;
        let msg: Record<string, unknown>;
        try {
          msg = JSON.parse(line) as Record<string, unknown>;
        } catch {
          continue;
        }
        const id = msg.id;
        if (typeof id === 'number' && pending.has(id)) {
          const cb = pending.get(id)!;
          pending.delete(id);
          cb(msg);
        } else if (typeof msg.method === 'string') {
          // Notification — read threadId from _meta (first occurrence suffices).
          if (!threadId) {
            const params = msg.params as { _meta?: { threadId?: unknown } } | undefined;
            const tid = params?._meta?.threadId;
            if (typeof tid === 'string' && tid.length > 0) threadId = tid;
          }
        }
      }
    });

    // ---- MCP-Handshake + tools/call ----
    void (async () => {
      try {
        await request('initialize', {
          protocolVersion: '2025-06-18',
          capabilities: {},
          clientInfo: { name: 'lazyos-imagegen', version: '1.0.0' },
        });
        notify('notifications/initialized', {});
        const res = await request('tools/call', {
          name: 'codex',
          arguments: {
            prompt: buildImagePrompt(opts.prompt),
            model,
            sandbox,
            'approval-policy': 'never',
            cwd: CODEX_HOME,
          },
        });
        if (settled) return;
        const err = res.error as { message?: string } | undefined;
        if (err) {
          fail(new NoImageProducedError(err.message ?? 'tools/call error'));
          return;
        }
        // No matter what the agent replies as text — we read the PNG from the
        // thread folder (deterministic, independent of the response text).
        resolveProducedPng();
      } catch (e) {
        fail(e instanceof Error ? e : new Error(String(e)));
      }
    })();
  });
}
