/**
 * lib/imagegen/codex-mcp.ts
 * -------------------------
 * Bild-Generierung über die Codex-MCP-Brücke (Owner-Wahl 2026-06-03).
 *
 * WARUM MCP statt `codex exec`?
 *   `codex exec` (non-interaktiv) hat KEINEN Zugriff auf das eingebaute
 *   `image_gen`-Tool (OpenAI-Issue #19133) — nur der interaktive Agent kann
 *   Bilder erzeugen. `codex mcp-server` (stdio) startet GENAU diesen vollen
 *   Agenten als MCP-Server und exponiert ein `codex`-Tool, das eine komplette
 *   Agent-Session fährt — inkl. `image_gen`. Kein OPENAI_API_KEY nötig; läuft
 *   über das lokale MAX-/ChatGPT-Abo (~/.codex/auth.json).
 *
 * VERIFIZIERT (2026-06-03, codex-cli 0.130.0): ein `tools/call` auf das
 * `codex`-Tool mit einem Bild-Prompt erzeugt eine echte PNG (~1 MB) unter
 * `~/.codex/generated_images/<threadId>/ig_*.png`. Latenz ~85 s (TTFT ~35 s).
 *
 * SICHERHEIT / DETERMINISMUS:
 *   - `sandbox: 'read-only'` (Default): der Agent darf KEINE Shell-/FS-Writes.
 *     Das `image_gen`-Tool schreibt über seinen eigenen privilegierten Pfad
 *     nach $CODEX_HOME — unabhängig vom Workspace-Sandbox. Read-only verhindert
 *     den beobachteten „ffmpeg-Umweg" (Modell versucht sonst, das Bild per
 *     Shell zu faken).
 *   - `approval-policy: 'never'`: non-interaktiv, keine Genehmigungs-Prompts.
 *   - Strikter Prompt: NUR `image_gen`, kein Shell/Python/ffmpeg.
 *   - Single-Flight (N11): max EINE Generierung gleichzeitig — Bild-Gen ist
 *     teuer (~85 s, gpt-image server-seitig). Parallele Aufrufe → `image_gen_busy`.
 *
 * Reines Node (child_process + fs). Kein React, kein Next-spezifischer Import —
 * importierbar aus einer API-Route ODER einem Test-Harness.
 */

import { spawn, type ChildProcessWithoutNullStreams } from 'node:child_process';
import { existsSync, readdirSync, statSync } from 'node:fs';
import { homedir } from 'node:os';
import { join } from 'node:path';

const CODEX_BIN = process.env.LAZYOS_CODEX_BIN ?? 'codex';
const CODEX_HOME = process.env.CODEX_HOME ?? join(homedir(), '.codex');
const GEN_DIR = join(CODEX_HOME, 'generated_images');
const DEFAULT_TIMEOUT_MS = 180_000; // 3 min — Bild-Gen läuft ~85 s, Puffer für Cold-Start.

/** Typed error für „eine Generierung läuft bereits" (N11 Single-Flight). */
export class ImageGenBusyError extends Error {
  constructor() {
    super('image_gen_busy');
    this.name = 'ImageGenBusyError';
  }
}

/** Typed error für „Agent hat kein Bild produziert" (Refusal / image_gen-Fehler). */
export class NoImageProducedError extends Error {
  constructor(detail: string) {
    super(`no_image_produced: ${detail}`);
    this.name = 'NoImageProducedError';
  }
}

export interface GenerateImageResult {
  /** Absoluter Pfad zur erzeugten PNG (unter ~/.codex/generated_images/...). */
  pngPath: string;
  /** Codex-Thread-/Conversation-ID (= Unterordner-Name), falls erfasst. */
  threadId: string | null;
  /** Latenz der Generierung in ms. */
  latencyMs: number;
}

interface PngEntry {
  path: string;
  mtimeMs: number;
}

/** Alle PNGs unter GEN_DIR auflisten (rekursiv über die Thread-Unterordner). */
function listPngs(restrictThreadId?: string | null): PngEntry[] {
  const out: PngEntry[] = [];
  if (!existsSync(GEN_DIR)) return out;
  const sessions = restrictThreadId ? [restrictThreadId] : readdirSync(GEN_DIR);
  for (const sess of sessions) {
    const sd = join(GEN_DIR, sess);
    let st;
    try {
      st = statSync(sd);
    } catch {
      continue;
    }
    if (!st.isDirectory()) continue;
    let files: string[];
    try {
      files = readdirSync(sd);
    } catch {
      continue;
    }
    for (const f of files) {
      if (!f.toLowerCase().endsWith('.png')) continue;
      const p = join(sd, f);
      try {
        out.push({ path: p, mtimeMs: statSync(p).mtimeMs });
      } catch {
        /* race: datei verschwand */
      }
    }
  }
  return out;
}

/**
 * Strikter System-/User-Prompt der den Agenten zwingt, NUR `image_gen` zu
 * verwenden (kein Shell-Umweg) und genau EIN Bild zu erzeugen.
 */
function buildImagePrompt(userPrompt: string): string {
  return [
    'You are a single-purpose image generation service.',
    'Use ONLY your built-in `image_gen` tool to create EXACTLY ONE image.',
    'Do NOT use shell commands, ffmpeg, python, ImageMagick, or any other method —',
    'ONLY the built-in `image_gen` tool. Do not attempt to write any files yourself.',
    'Do not ask clarifying questions; make reasonable choices and generate directly.',
    '',
    'Image to generate (verbatim user request):',
    userPrompt,
    '',
    'After the image has been generated by `image_gen`, reply with ONLY the word DONE.',
  ].join('\n');
}

// N11 — Single-Flight: nur EINE Generierung gleichzeitig.
let inFlight = false;

/**
 * Erzeugt ein Bild über die Codex-MCP-Brücke und liefert den lokalen PNG-Pfad.
 *
 * @throws {ImageGenBusyError}     wenn bereits eine Generierung läuft.
 * @throws {NoImageProducedError}  wenn kein neues PNG entstand.
 * @throws {Error}                 bei Spawn-/Timeout-/Abort-Fehlern.
 */
export async function generateImageViaCodex(opts: {
  prompt: string;
  signal?: AbortSignal;
  timeoutMs?: number;
  sandbox?: 'read-only' | 'workspace-write';
  model?: string;
}): Promise<GenerateImageResult> {
  if (inFlight) throw new ImageGenBusyError();
  inFlight = true;
  try {
    return await runGeneration(opts);
  } finally {
    inFlight = false;
  }
}

function runGeneration(opts: {
  prompt: string;
  signal?: AbortSignal;
  timeoutMs?: number;
  sandbox?: 'read-only' | 'workspace-write';
  model?: string;
}): Promise<GenerateImageResult> {
  const t0 = Date.now();
  const timeoutMs = opts.timeoutMs ?? DEFAULT_TIMEOUT_MS;
  const sandbox = opts.sandbox ?? 'read-only';
  const model = opts.model || process.env.LAZYOS_IMAGEGEN_MODEL || 'gpt-5.5';

  // Baseline-PNGs VOR dem Lauf — Fallback-Erkennung falls die threadId nicht
  // aus den Notifications zu lesen ist.
  const before = new Set(listPngs().map((x) => x.path));

  return new Promise<GenerateImageResult>((resolve, reject) => {
    let child: ChildProcessWithoutNullStreams;
    try {
      child = spawn(CODEX_BIN, ['mcp-server'], { stdio: ['pipe', 'pipe', 'pipe'] });
    } catch (err) {
      reject(err instanceof Error ? err : new Error(String(err)));
      return;
    }

    let buf = '';
    let nextId = 1;
    let threadId: string | null = null;
    let settled = false;
    const pending = new Map<number, (msg: Record<string, unknown>) => void>();
    let stderrTail = '';

    const cleanup = (): void => {
      try {
        child.kill('SIGTERM');
      } catch {
        /* ignore */
      }
      clearTimeout(timer);
      if (opts.signal) opts.signal.removeEventListener('abort', onAbort);
    };
    const done = (
      fn: () => void,
    ): void => {
      if (settled) return;
      settled = true;
      cleanup();
      fn();
    };
    const fail = (err: Error): void => done(() => reject(err));

    const timer = setTimeout(() => {
      fail(new Error(`codex-imagegen timeout after ${timeoutMs}ms`));
    }, timeoutMs);

    const onAbort = (): void => fail(new Error('aborted'));
    if (opts.signal) {
      if (opts.signal.aborted) {
        fail(new Error('aborted'));
        return;
      }
      opts.signal.addEventListener('abort', onAbort, { once: true });
    }

    const writeMsg = (obj: Record<string, unknown>): void => {
      try {
        child.stdin.write(JSON.stringify(obj) + '\n');
      } catch (err) {
        fail(err instanceof Error ? err : new Error(String(err)));
      }
    };
    const request = (
      method: string,
      params: Record<string, unknown>,
    ): Promise<Record<string, unknown>> => {
      const id = nextId++;
      writeMsg({ jsonrpc: '2.0', id, method, params });
      return new Promise((res) => pending.set(id, res));
    };
    const notify = (method: string, params: Record<string, unknown>): void => {
      writeMsg({ jsonrpc: '2.0', method, params });
    };

    /** Locate the freshest PNG produced by this run. */
    const resolveProducedPng = (): void => {
      // Bevorzugt: nur der Thread-Ordner dieses Laufs.
      let candidates = listPngs(threadId).filter((p) => !before.has(p.path));
      // Fallback: irgendein neues PNG global (threadId nicht erfasst).
      if (candidates.length === 0) {
        candidates = listPngs().filter((p) => !before.has(p.path));
      }
      if (candidates.length === 0) {
        fail(new NoImageProducedError('kein neues PNG unter ~/.codex/generated_images'));
        return;
      }
      candidates.sort((a, b) => b.mtimeMs - a.mtimeMs);
      done(() =>
        resolve({
          pngPath: candidates[0]!.path,
          threadId,
          latencyMs: Date.now() - t0,
        }),
      );
    };

    child.on('error', (err) => fail(err));
    child.stderr.on('data', (d: Buffer) => {
      stderrTail = (stderrTail + d.toString('utf8')).slice(-2000);
    });
    child.on('exit', (code) => {
      // Sauberer Exit ohne Resolve = Fehler.
      if (!settled) {
        fail(
          new Error(
            `codex mcp-server exited (code ${code}) before producing an image. stderr: ${stderrTail.slice(-400)}`,
          ),
        );
      }
    });

    child.stdout.on('data', (d: Buffer) => {
      buf += d.toString('utf8');
      let nl: number;
      while ((nl = buf.indexOf('\n')) >= 0) {
        const line = buf.slice(0, nl).trim();
        buf = buf.slice(nl + 1);
        if (!line) continue;
        let msg: Record<string, unknown>;
        try {
          msg = JSON.parse(line) as Record<string, unknown>;
        } catch {
          continue;
        }
        const id = msg.id;
        if (typeof id === 'number' && pending.has(id)) {
          const cb = pending.get(id)!;
          pending.delete(id);
          cb(msg);
        } else if (typeof msg.method === 'string') {
          // Notification — threadId aus _meta lesen (erstes Auftreten genügt).
          if (!threadId) {
            const params = msg.params as { _meta?: { threadId?: unknown } } | undefined;
            const tid = params?._meta?.threadId;
            if (typeof tid === 'string' && tid.length > 0) threadId = tid;
          }
        }
      }
    });

    // ---- MCP-Handshake + tools/call ----
    void (async () => {
      try {
        await request('initialize', {
          protocolVersion: '2025-06-18',
          capabilities: {},
          clientInfo: { name: 'lazyos-imagegen', version: '1.0.0' },
        });
        notify('notifications/initialized', {});
        const res = await request('tools/call', {
          name: 'codex',
          arguments: {
            prompt: buildImagePrompt(opts.prompt),
            model,
            sandbox,
            'approval-policy': 'never',
            cwd: CODEX_HOME,
          },
        });
        if (settled) return;
        const err = res.error as { message?: string } | undefined;
        if (err) {
          fail(new NoImageProducedError(err.message ?? 'tools/call error'));
          return;
        }
        // Egal was der Agent als Text antwortet — wir lesen das PNG aus dem
        // Thread-Ordner (deterministisch, unabhängig vom Antworttext).
        resolveProducedPng();
      } catch (e) {
        fail(e instanceof Error ? e : new Error(String(e)));
      }
    })();
  });
}
